githubRepoOwner: inigolabs
githubRepoName: stopwatch
githubHost: github.com
requireChecks: false
requireApproval: false
githubRemote: origin
githubBranch: main
remoteBranches: []
mergeMethod: rebase
mergeQueue: false
forceFetchTags: false
